[package]
name = "swc-plugin-evaluate-polyfills"
description = "An SWC plugin that statically evaluates inline polyfill checks at build time."
version = "0.1.0"
edition = "2021"
authors = ["Alexander Zaytsev <zaytsev126@gmail.com>"]
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
panic = "abort"

[dependencies]
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
swc_core = { version = "^80.0.*", features = [
  "ecma_ast",
  "ecma_plugin_transform",
] }

[dev-dependencies]
testing = "27.0.0"
swc_core = { version = "^80.0.*", features = [
  "ecma_parser",
  "testing_transform",
] }
